/******************************************************
 * Module Name    : VASLogic
 * Purpose        : Recently Generated Records widget data
 * chronological  : Development
 * Created Date   : 2026-08-31
 * Created by     : VAI145
 ******************************************************/

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using VAdvantage.DataBase;
using VAdvantage.Logging;
using VAdvantage.Model;
using VAdvantage.Utility;

namespace VASLogic.Models
{
    /// <summary>
    /// Module Name : VAS_224_RecentlyGenerated
    /// Purpose     : Backs the VAS_224_RecentlyGeneratedRecords dashboard widget
    ///               (Recurring module, 6x2 grid). Answers "which records were
    ///               generated by recurring runs in the last 30 days?".
    ///
    ///               Built as a CTE over one UNION ALL branch per document type a
    ///               recurring run can produce. Each branch INNER JOINs its own
    ///               document table, so a run whose document has since been removed
    ///               drops out rather than showing as an empty row.
    ///
    ///               MRole handling follows the CTE rule exactly:
    ///                 - AddAccessSQL is applied INSIDE every UNION branch, on the
    ///                   main physical alias rr (C_Recurring_Run), before the
    ///                   branches are combined;
    ///                 - it is NEVER applied to the CTE alias GeneratedDocs, which is
    ///                   a derived result set with no AD_Table behind it, nor to the
    ///                   final combined statement;
    ///                 - the joined document, partner and currency tables are lookups
    ///                   and inherit the filter their branch already carries.
    ///               The CTE result is therefore already security-filtered before the
    ///               outer SELECT consumes it.
    ///
    ///               The 30-day bound is a bound parameter computed server side, not
    ///               CURRENT_DATE / TRUNC(SYSDATE) written per backend: one statement
    ///               then runs unchanged on PostgreSQL and Oracle, and comparing the
    ///               raw column keeps it index-usable.
    ///
    ///               No display text is produced by the query. Each branch emits the
    ///               stored RecurringType code and the client resolves the label from
    ///               AD_Message. Amounts are reported UNCONVERTED, in the generated
    ///               document's own currency, which the outer SELECT resolves once.
    ///
    ///               The tenant always comes from the authenticated context; the
    ///               client never supplies AD_Client_ID or a date.
    /// Chronological development:
    ///   VAI154      2026-08-31 Created
    /// </summary>
    public class VAS_224_RecentlyGeneratedModel
    {
        private static readonly VLogger Log = VLogger.GetVLogger(typeof(VAS_224_RecentlyGeneratedModel).FullName);

        /// <summary>Default rows per page when the client asks for none.</summary>
        public const int PAGESIZE_DEFAULT = 6;

        /// <summary>Largest accepted page size - the widget sizes its own page from
        /// the cell height, so anything beyond this is not a real request.</summary>
        public const int PAGESIZE_MAX = 50;

        /// <summary>Look-back window, in days, matching the widget design.</summary>
        public const int WINDOW_DAYS = 30;

        /* Document type codes, aligned with C_Recurring.RecurringType so the whole
           Recurring family shares one label map on the client. */
        public const string DOCTYPE_GLJournal = "B";
        public const string DOCTYPE_GLJournalBatch = "G";
        public const string DOCTYPE_Invoice = "I";
        public const string DOCTYPE_Project = "J";
        public const string DOCTYPE_Order = "O";
        public const string DOCTYPE_Payment = "P";

        /// <summary>
        /// Returns one page of the documents generated by recurring runs inside the
        /// look-back window, newest first.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <param name="page">Zero-based page index; negative values are treated as 0.</param>
        /// <param name="pageSize">Rows per page; clamped to [1, PAGESIZE_MAX].</param>
        /// <returns>Populated <see cref="RecentlyGeneratedPage"/> (never null). Loaded
        /// is false only when the context is missing or a query failed; a tenant that
        /// generated nothing returns Loaded=true with an empty list.</returns>
        public RecentlyGeneratedPage GetRecentlyGenerated(Ctx ctx, int page, int pageSize)
        {
            RecentlyGeneratedPage result = new RecentlyGeneratedPage();
            result.Loaded = false;
            result.Rows = new List<RecentlyGeneratedRow>();

            if (ctx == null) { return result; }

            /* Paging inputs arrive from the client, so they are clamped rather than
               trusted - an unbounded page size would defeat the point of paging. */
            if (page < 0) { page = 0; }
            if (pageSize <= 0) { pageSize = PAGESIZE_DEFAULT; }
            if (pageSize > PAGESIZE_MAX) { pageSize = PAGESIZE_MAX; }

            result.Page = page;
            result.PageSize = pageSize;
            result.WindowDays = WINDOW_DAYS;

            DateTime dateFrom = DateTime.Now.Date.AddDays(-WINDOW_DAYS);
            result.DateFrom = dateFrom.ToString("yyyy-MM-dd");

            try
            {
                /* Count first, so the pager knows the dataset size and a page index
                   past the end can be corrected instead of returning an empty list
                   with no explanation. */
                result.TotalRows = CountGenerated(ctx, dateFrom);

                int totalPages = result.TotalRows > 0
                    ? (int)Math.Ceiling((double)result.TotalRows / pageSize)
                    : 1;
                if (page > totalPages - 1) { page = totalPages - 1; }
                if (page < 0) { page = 0; }
                result.Page = page;

                if (result.TotalRows > 0)
                {
                    LoadRows(ctx, dateFrom, page * pageSize, pageSize, result);
                }

                result.Loaded = true;
            }
            catch (Exception ex)
            {
                /* Caught here so the caller can tell "query failed" apart from
                   "nothing was generated" - the widget renders those two cases
                   differently. */
                Log.Log(Level.SEVERE, "VAS_224_RecentlyGenerated.GetRecentlyGenerated AD_Client_ID="
                    + ctx.GetAD_Client_ID() + " Page=" + page, ex);
                result.Loaded = false;
                result.Rows.Clear();
            }

            return result;
        }

        /// <summary>
        /// Counts the generated documents in the window. Shares its CTE with
        /// <see cref="LoadRows"/> so the pager total can never disagree with the rows
        /// behind it.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <param name="dateFrom">First day of the look-back window.</param>
        /// <returns>Number of generated documents.</returns>
        private int CountGenerated(Ctx ctx, DateTime dateFrom)
        {
            string sql = BuildGeneratedDocsCte(ctx) + @"
                SELECT COUNT(1) AS Generated_Count
                FROM GeneratedDocs g";

            /* No AddAccessSQL here. GeneratedDocs is a derived result set, not a
               physical table - it cannot be resolved through AD_Table metadata, and
               every branch inside it is already access-filtered. */
            return Util.GetValueOfInt(DB.ExecuteScalar(sql, BuildBranchParameters(ctx, dateFrom), null));
        }

        /// <summary>
        /// Reads one page of generated documents and folds each into a display-ready
        /// record.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <param name="dateFrom">First day of the look-back window.</param>
        /// <param name="offset">Rows to skip.</param>
        /// <param name="pageSize">Rows to fetch.</param>
        /// <param name="result">Page envelope whose Rows list is filled in.</param>
        /// <returns>void</returns>
        private void LoadRows(Ctx ctx, DateTime dateFrom, int offset, int pageSize, RecentlyGeneratedPage result)
        {
            /* The currency descriptors are resolved once on the outer SELECT rather
               than joined inside all six branches. C_Currency is a reference table
               hanging off the already-filtered CTE, so it needs no MRole of its own. */
            string sql = BuildGeneratedDocsCte(ctx) + @"
                SELECT g.Run_Id AS Run_Id,
                       g.Generated_Date AS Generated_Date,
                       g.Document_No AS Document_No,
                       g.Document_Type AS Document_Type,
                       g.BPartner_Name AS BPartner_Name,
                       g.Amount_Document AS Amount_Document,
                       cur.ISO_Code AS Amount_Currency_Iso,
                       cur.CurSymbol AS Amount_Currency_Symbol,
                       cur.StdPrecision AS Amount_Currency_Precision
                FROM GeneratedDocs g
                LEFT OUTER JOIN C_Currency cur ON (cur.C_Currency_ID=g.Amount_Currency_ID)
                ORDER BY g.Generated_Date DESC,g.Run_Id DESC";

            sql += PagingSuffix(pageSize, offset);

            DataSet ds = DB.ExecuteDataset(sql, BuildBranchParameters(ctx, dateFrom), null);
            if (ds == null || ds.Tables.Count == 0) { return; }

            DataTable dt = ds.Tables[0];
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                DataRow dr = dt.Rows[i];

                DateTime? generated = Util.GetValueOfDateTime(dr["Generated_Date"]);

                /* Standard precision of the row's OWN currency, so a zero-decimal
                   currency is not printed with two. Defaults to 2 when the generated
                   document carries no currency (a project run). */
                int precision = Util.GetValueOfInt(dr["Amount_Currency_Precision"]);
                if (precision < 0 || precision > 6) { precision = 2; }

                RecentlyGeneratedRow row = new RecentlyGeneratedRow();
                row.C_Recurring_Run_ID = Util.GetValueOfInt(dr["Run_Id"]);
                row.GeneratedDate = generated.HasValue ? generated.Value.ToString("yyyy-MM-dd") : "";
                row.DocumentNo = Util.GetValueOfString(dr["Document_No"]);
                row.DocumentType = Util.GetValueOfString(dr["Document_Type"]);
                row.BPartnerName = Util.GetValueOfString(dr["BPartner_Name"]);
                row.Amount = Util.GetValueOfDecimal(dr["Amount_Document"]);
                row.AmountCurrencyIso = Util.GetValueOfString(dr["Amount_Currency_Iso"]);
                row.AmountCurrencySymbol = Util.GetValueOfString(dr["Amount_Currency_Symbol"]);
                row.AmountPrecision = precision;

                result.Rows.Add(row);
            }
        }

        // ─────────────────────────────────────────────────────────────────────
        // §2  The CTE
        // ─────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Builds the GeneratedDocs CTE: one UNION ALL branch per document type a
        /// recurring run can produce, each independently wrapped with MRole on its own
        /// main physical alias (rr) before the branches are combined.
        ///
        /// The build pack's query covers four branches. GL journal batches and
        /// projects are included here as well because MRecurring.ExecuteRun can create
        /// both, and leaving them out would silently under-report what the recurring
        /// process generated.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <returns>WITH clause, ending in a newline ready for the outer SELECT.</returns>
        private string BuildGeneratedDocsCte(Ctx ctx)
        {
            StringBuilder cte = new StringBuilder();
            cte.Append(@"
                WITH GeneratedDocs AS (");

            cte.Append(Branch(ctx, 1, DOCTYPE_Invoice,
                "INNER JOIN C_Invoice doc ON (doc.C_Invoice_ID=rr.C_Invoice_ID)",
                "LEFT OUTER JOIN C_BPartner bp ON (bp.C_BPartner_ID=doc.C_BPartner_ID)",
                "doc.DocumentNo", "bp.Name", "COALESCE(doc.GrandTotal,0)", "doc.C_Currency_ID"));

            cte.Append(@"
                UNION ALL");
            cte.Append(Branch(ctx, 2, DOCTYPE_Order,
                "INNER JOIN C_Order doc ON (doc.C_Order_ID=rr.C_Order_ID)",
                "LEFT OUTER JOIN C_BPartner bp ON (bp.C_BPartner_ID=doc.C_BPartner_ID)",
                "doc.DocumentNo", "bp.Name", "COALESCE(doc.GrandTotal,0)", "doc.C_Currency_ID"));

            cte.Append(@"
                UNION ALL");
            cte.Append(Branch(ctx, 3, DOCTYPE_Payment,
                "INNER JOIN C_Payment doc ON (doc.C_Payment_ID=rr.C_Payment_ID)",
                "LEFT OUTER JOIN C_BPartner bp ON (bp.C_BPartner_ID=doc.C_BPartner_ID)",
                "doc.DocumentNo", "bp.Name", "COALESCE(doc.PayAmt,0)", "doc.C_Currency_ID"));

            /* GL documents post against the ledger and carry no partner, so these two
               branches take no partner join at all and select a bare NULL in that
               position. The union resolves the column's type from the branches above,
               which is why the partner-bearing branches come first. */
            cte.Append(@"
                UNION ALL");
            cte.Append(Branch(ctx, 4, DOCTYPE_GLJournal,
                "INNER JOIN GL_Journal doc ON (doc.GL_Journal_ID=rr.GL_Journal_ID)",
                "",
                "doc.DocumentNo", "NULL", "COALESCE(doc.TotalDr,0)", "doc.C_Currency_ID"));

            cte.Append(@"
                UNION ALL");
            cte.Append(Branch(ctx, 5, DOCTYPE_GLJournalBatch,
                "INNER JOIN GL_JournalBatch doc ON (doc.GL_JournalBatch_ID=rr.GL_JournalBatch_ID)",
                "",
                "doc.DocumentNo", "NULL", "COALESCE(doc.TotalDr,0)", "doc.C_Currency_ID"));

            /* A project is identified by its Value and has no document total or
               currency of its own. */
            cte.Append(@"
                UNION ALL");
            cte.Append(Branch(ctx, 6, DOCTYPE_Project,
                "INNER JOIN C_Project doc ON (doc.C_Project_ID=rr.C_Project_ID)",
                "LEFT OUTER JOIN C_BPartner bp ON (bp.C_BPartner_ID=doc.C_BPartner_ID)",
                "doc.Value", "bp.Name", "0", "doc.C_Currency_ID"));

            cte.Append(@"
                )");

            return cte.ToString();
        }

        /// <summary>
        /// One UNION branch, access-filtered on its own. Every branch selects the same
        /// column list in the same order so the union is well-formed, and carries its
        /// own uniquely named binds because the provider binds positionally.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <param name="index">1-based branch number; suffixes this branch's binds.</param>
        /// <param name="typeCode">Stored document type code this branch emits.</param>
        /// <param name="documentJoin">INNER JOIN onto the generated document table, aliased doc.</param>
        /// <param name="partnerJoin">LEFT OUTER JOIN onto C_BPartner, aliased bp.</param>
        /// <param name="documentNoExpression">Column holding the document's identifier.</param>
        /// <param name="partnerNameExpression">Column holding the partner name.</param>
        /// <param name="amountExpression">Column or literal holding the document total.</param>
        /// <param name="currencyExpression">Column holding the document currency id.</param>
        /// <returns>Access-filtered SELECT for this branch.</returns>
        private string Branch(Ctx ctx, int index, string typeCode,
            string documentJoin, string partnerJoin,
            string documentNoExpression, string partnerNameExpression,
            string amountExpression, string currencyExpression)
        {
            string sql = @"
                SELECT rr.C_Recurring_Run_ID AS Run_Id,
                       rr.DateDoc AS Generated_Date,
                       " + documentNoExpression + @" AS Document_No,
                       '" + typeCode + @"' AS Document_Type,
                       " + partnerNameExpression + @" AS BPartner_Name,
                       " + amountExpression + @" AS Amount_Document,
                       " + currencyExpression + @" AS Amount_Currency_ID
                FROM C_Recurring_Run rr
                " + documentJoin + @"
                " + partnerJoin + @"
                WHERE rr.IsActive='Y'
                  AND rr.AD_Client_ID IN (@AD_Client_ID_" + index + @")
                  AND rr.DateDoc>=@DateFrom_" + index;

            /* MRole on the MAIN PHYSICAL table of this branch only (C_Recurring_Run /
               alias rr). The joined document and partner tables are lookups feeding
               this branch, not the source the user is fetching from, and inherit the
               filter. Applied here, per branch - never on the combined statement and
               never on the GeneratedDocs alias. */
            return MRole.GetDefault(ctx).AddAccessSQL(sql, "rr", MRole.SQL_FULLYQUALIFIED, MRole.SQL_RO);
        }

        /// <summary>
        /// The binds for every branch, in the order their placeholders appear in the
        /// combined statement. Each occurrence carries a unique name because the
        /// provider binds positionally, so six branches means six client binds and six
        /// date binds rather than one of each reused.
        /// </summary>
        /// <param name="ctx">Session context (client / org / role).</param>
        /// <param name="dateFrom">First day of the look-back window.</param>
        /// <returns>Parameter array in statement order.</returns>
        private SqlParameter[] BuildBranchParameters(Ctx ctx, DateTime dateFrom)
        {
            const int branchCount = 6;
            int clientId = ctx.GetAD_Client_ID();

            List<SqlParameter> parameters = new List<SqlParameter>();
            for (int index = 1; index <= branchCount; index++)
            {
                parameters.Add(new SqlParameter("@AD_Client_ID_" + index, clientId));
                parameters.Add(new SqlParameter("@DateFrom_" + index, dateFrom));
            }

            return parameters.ToArray();
        }

        /// <summary>
        /// Database-specific paging suffix: OFFSET / FETCH on Oracle, LIMIT / OFFSET
        /// elsewhere. Both values are server-clamped integers, never client text.
        /// </summary>
        /// <param name="pageSize">Rows to fetch.</param>
        /// <param name="offset">Rows to skip.</param>
        /// <returns>Paging clause.</returns>
        private string PagingSuffix(int pageSize, int offset)
        {
            if (pageSize <= 0) { pageSize = PAGESIZE_DEFAULT; }
            if (offset < 0) { offset = 0; }

            if (DB.IsOracle())
            {
                return " OFFSET " + offset + " ROWS FETCH NEXT " + pageSize + " ROWS ONLY";
            }
            return " LIMIT " + pageSize + " OFFSET " + offset;
        }

        // ─────────────────────────────────────────────────────────────────────
        // §3  Contracts
        // ─────────────────────────────────────────────────────────────────────

        /// <summary>One page of the recently-generated list.</summary>
        public class RecentlyGeneratedPage
        {
            /// <summary>False only when the data could not be read. A tenant that
            /// generated nothing is Loaded=true with an empty list.</summary>
            public bool Loaded { get; set; }

            /// <summary>Zero-based page index actually served, after clamping.</summary>
            public int Page { get; set; }

            public int PageSize { get; set; }

            /// <summary>Size of the whole dataset, not of this page.</summary>
            public int TotalRows { get; set; }

            /// <summary>Resolved look-back window in days.</summary>
            public int WindowDays { get; set; }

            /// <summary>First day of the window, yyyy-MM-dd. Formatted for display client-side.</summary>
            public string DateFrom { get; set; }

            public List<RecentlyGeneratedRow> Rows { get; set; }
        }

        /// <summary>One document produced by a recurring run.</summary>
        public class RecentlyGeneratedRow
        {
            public int C_Recurring_Run_ID { get; set; }

            /// <summary>yyyy-MM-dd. Date formatting for display is done client-side.</summary>
            public string GeneratedDate { get; set; }

            /// <summary>Document number of the generated document (a project uses its
            /// Value).</summary>
            public string DocumentNo { get; set; }

            /// <summary>Stored DOCTYPE_* code; the client resolves the label.</summary>
            public string DocumentType { get; set; }

            /// <summary>Partner of the generated document; empty for GL documents,
            /// which the client renders as an empty cell.</summary>
            public string BPartnerName { get; set; }

            /// <summary>Generated-document amount, untouched and in its own currency -
            /// nothing is converted.</summary>
            public decimal Amount { get; set; }

            public string AmountCurrencyIso { get; set; }
            public string AmountCurrencySymbol { get; set; }
            public int AmountPrecision { get; set; }
        }
    }
}
