using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VAdvantage.Utility;
using System.Data;
using VAdvantage.Logging;
using VAdvantage.DataBase;
using VAdvantage.ProcessEngine;
using VAdvantage.Model;
using ModelLibrary.Classes;
using ModelLibrary.Model;

/* Writer :VAI052
* Date   : 01-Jun-26
*
* Cloned from ViennaAdvantage.Process.ProspectToOpportunity
* (Process\ViennaAdvantageProcess\ProspectToOpportunity.cs).
*
* The generated record was switched from VAdvantage.Model.X_C_Project to
* ModelLibrary.Model.X_VAS_Opportunity (the dedicated opportunity table).
* Because the two tables expose different columns, the field mapping was
* adapted as follows (every spot is also commented inline):
*
*   - Typed setters that have NO counterpart on X_VAS_Opportunity and only
*     make sense for the dual-purpose C_Project table are dropped:
*       SetDateContract (PO "Created" already records the creation date).
*   - GetC_Project_ID() -> GetVAS_Opportunity_ID() and the history/AI table id is
*     taken from opp.Get_Table_ID() (the VAS_Opportunity table).
*   - The lead.SetC_Project_ID(...) back-link is replaced with a guarded write to
*     the lead's VAS_Opportunity_ID column (if present); C_Project_ID is a project
*     foreign key and must not hold an opportunity id.
*/
namespace ModelLibrary.Process
{
    public class VAS_ProspectToOpportunity : SvrProcess
    {
        int _C_Lead_ID;
        protected override void Prepare()
        {

        }

        /// <summary>
        /// Doit
        /// </summary>
        /// <returns>message</returns>
        protected override string DoIt()
        {
            X_C_BPartner partner = new X_C_BPartner(GetCtx(), GetRecord_ID(), null);
            string _BPName = partner.GetName();
            string _retVal = "";
            string _sql = "SELECT C_Lead_ID FROM C_Lead Where BPName='" + _BPName + "'  AND IsActive = 'Y' AND AD_Client_ID = " + GetAD_Client_ID();
            DataSet ds = DB.ExecuteDataset(_sql.ToString());
            if (ds != null && ds.Tables != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    _C_Lead_ID = Util.GetValueOfInt(ds.Tables[0].Rows[i]["C_Lead_ID"]);
                    X_C_Lead lead = new X_C_Lead(GetCtx(), _C_Lead_ID, Get_TrxName());

                    int Pospect = lead.GetRef_BPartner_ID();

                    if (Pospect != 0)
                    {
                        X_VAS_Opportunity opp = new X_VAS_Opportunity(GetCtx(), 0, Get_TrxName());
                        X_C_BPartner bp = new X_C_BPartner(GetCtx(), Pospect, Get_TrxName());
                        //VIA051:- Implement IsCustomer check to verify opportunity is generated by customer or Prospect
                        if (bp.IsCustomer())
                        {
                            opp.SetC_BPartner_ID(bp.GetC_BPartner_ID());

                        }
                        else
                        {
                            opp.SetC_BPartnerSR_ID(lead.GetRef_BPartner_ID());

                        }
                        opp.SetC_Lead_ID(lead.GetC_Lead_ID());
                        opp.SetName(bp.GetName());
                        opp.SetDescription(lead.GetDescription());
                        opp.SetSalesRep_ID(lead.GetSalesRep_ID());
                        opp.SetC_Campaign_ID(lead.GetC_Campaign_ID());
                        opp.SetAD_User_ID(lead.GetAD_User_ID());
                        opp.SetC_BPartner_Location_ID(lead.GetC_BPartner_Location_ID());
                        opp.SetIsOpportunity(true);
                        opp.SetRef_BPartner_ID(lead.GetRef_BPartner_ID());
                        opp.SkipAIAssistantThreadUpdate = true;
                        if (opp.Save())
                        {
                            //Save history chat data form prospect window to opportunity window

                            int FromTableID = partner.Get_Table_ID();
                            int ToTableID = opp.Get_Table_ID();
                            VAS_CommonMethod.CopyHistorRecordData(FromTableID, ToTableID, opp.GetVAS_Opportunity_ID(), GetRecord_ID(), Get_TrxName(), GetCtx());
                            // C_Project_ID is a project FK; link the lead to the new opportunity
                            // through its VAS_Opportunity_ID column instead (when available).
                            if (lead.Get_ColumnIndex("VAS_Opportunity_ID") >= 0)
                            {
                                lead.Set_Value("VAS_Opportunity_ID", opp.GetVAS_Opportunity_ID());
                            }
                            lead.SetProcessed(true);
                            lead.Save();

                            bp.SetCreateProject("Y");
                            // Send Lead Data to Knowledge Base
                            VAS_CommonMethod.SendInfoToAI(lead.Get_Table_ID(), lead.Get_ID(), Get_Trx(), GetCtx());
                            // Send opp Data to Knowledge Base
                            VAS_CommonMethod.SendInfoToAI(opp.Get_Table_ID(), opp.Get_ID(), Get_Trx(), GetCtx());
                            if (bp.Save())
                            {
                            }

                            _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateDone");
                        }
                        else
                        {
                            _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateNotDone");
                        }
                    }
                }

            }
            else if (Env.IsModuleInstalled("VA047_"))
            {
                int val = Util.GetValueOfInt(DB.ExecuteScalar("SELECT AD_User_ID FROM AD_User WHERE C_BPartner_ID=" + partner.GetC_BPartner_ID(), null, Get_TrxName())); ;
                X_VAS_Opportunity opp = new X_VAS_Opportunity(GetCtx(), 0, Get_TrxName());
                MUser user = new MUser(GetCtx(), val, Get_TrxName());
                opp.SetSalesRep_ID(partner.GetSalesRep_ID());
                opp.SetName(partner.GetName());
                opp.SetDescription(partner.GetDescription());
                opp.SetC_BPartnerSR_ID(partner.GetC_BPartner_ID());
                opp.SetAD_User_ID(user.GetAD_User_ID());
                opp.SetC_BPartner_Location_ID(user.GetC_BPartner_Location_ID());
                opp.SetC_Campaign_ID(partner.GetC_Campaign_ID());
                opp.SetIsOpportunity(true);
                opp.SkipAIAssistantThreadUpdate = true;
                if (opp.Save())
                {
                    int FromTableID = partner.Get_Table_ID();
                    int ToTableID = opp.Get_Table_ID();
                    VAS_CommonMethod.CopyHistorRecordData(FromTableID, ToTableID, opp.GetVAS_Opportunity_ID(), GetRecord_ID(), Get_TrxName(), GetCtx());
                    partner.SetCreateProject("Y");
                    // Send opp Data to Knowledge Base
                    VAS_CommonMethod.SendInfoToAI(opp.Get_Table_ID(), opp.Get_ID(), Get_Trx(), GetCtx());
                    if (partner.Save())
                    {
                    }
                    _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateDone");
                }
                else
                {
                    _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateNotDone");
                }
            }
            return _retVal;


        }
    }
}
