/******************************************************
 * Module Name    : VAS
 * Purpose        : Records Generated dashboard widget endpoint
 * chronological  : Development
 * Created Date   : 2026-08-31
 * Created by     : VAI154
 ******************************************************/

using Newtonsoft.Json;
using System;
using System.Web.Mvc;
using VAdvantage.Logging;
using VAdvantage.Utility;
using VASLogic.Models;
using VIS.Filters;

namespace VAS.Controllers
{
    /// <summary>
    /// Module Name : VAS_221_RecordGeneratedWidget
    /// Purpose     : Thin AJAX endpoints for the Records Generated dashboard widget
    ///               (Recurring module). All business logic lives in
    ///               VASLogic.Models.VAS_221_RecordGeneratedModel; this controller
    ///               only resolves the session context and serializes the model
    ///               result.
    ///               The KPI figures and the drill-down list are separate calls
    ///               because the list can run to four figures and is paged in the
    ///               database - the card must not pay for rows nobody has opened yet.
    ///               The tenant is always taken from the authenticated context, and
    ///               the reporting period is always derived server side - the client
    ///               supplies neither AD_Client_ID nor a date range.
    /// Chronological development:
    ///   VAI154      2026-08-31 Created
    /// </summary>
    public class VAS_221_RecordGeneratedWidgetController : Controller
    {
        private static readonly VLogger Log = VLogger.GetVLogger(typeof(VAS_221_RecordGeneratedWidgetController).FullName);

        /// <summary>
        /// Returns the number of records generated by recurring runs in the tenant's
        /// current accounting period, the comparable figure for the preceding period,
        /// and the change between them.
        /// </summary>
        /// <returns>JSON-serialized RecordsGeneratedInfo, "" when there is no
        /// session, or an { error } payload when the lookup fails.</returns>
        [AjaxAuthorizeAttribute]
        [AjaxSessionFilterAttribute]
        public JsonResult GetRecordsGenerated()
        {
            string retJSON = "";

            if (Session["ctx"] != null)
            {
                Ctx ctx = Session["ctx"] as Ctx;
                try
                {
                    VAS_221_RecordGeneratedModel model = new VAS_221_RecordGeneratedModel();
                    retJSON = JsonConvert.SerializeObject(model.GetRecordsGenerated(ctx));
                }
                catch (Exception ex)
                {
                    Log.Log(Level.SEVERE, "VAS_221_RecordGeneratedWidget.GetRecordsGenerated", ex);
                    retJSON = JsonConvert.SerializeObject(new { error = true });
                }
            }

            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Returns one page of the documents generated by recurring runs in the
        /// tenant's current accounting period, newest first.
        /// </summary>
        /// <param name="page">Zero-based page index. Optional; defaults to the first
        /// page and is clamped in the model.</param>
        /// <param name="pageSize">Rows per page. Optional; defaults to the model's
        /// page size and is clamped there, so an out-of-range or hostile value cannot
        /// pull an unbounded result set.</param>
        /// <returns>JSON-serialized GeneratedRecordsPage, "" when there is no
        /// session, or an { error } payload when the lookup fails.</returns>
        [AjaxAuthorizeAttribute]
        [AjaxSessionFilterAttribute]
        public JsonResult GetGeneratedRecords(int? page, int? pageSize)
        {
            string retJSON = "";

            if (Session["ctx"] != null)
            {
                Ctx ctx = Session["ctx"] as Ctx;
                try
                {
                    int pageIndex = page.HasValue ? page.Value : 0;
                    int size = pageSize.HasValue ? pageSize.Value : VAS_221_RecordGeneratedModel.PAGESIZE_DEFAULT;

                    VAS_221_RecordGeneratedModel model = new VAS_221_RecordGeneratedModel();
                    retJSON = JsonConvert.SerializeObject(model.GetGeneratedRecords(ctx, pageIndex, size));
                }
                catch (Exception ex)
                {
                    Log.Log(Level.SEVERE, "VAS_221_RecordGeneratedWidget.GetGeneratedRecords", ex);
                    retJSON = JsonConvert.SerializeObject(new { error = true });
                }
            }

            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }
    }
}
