/******************************************************
 * Module Name    : VAS
 * Purpose        : Recently Generated Records widget endpoint
 * chronological  : Development
 * Created Date   : 2026-08-31
 * Created by     : VAI154
 ******************************************************/

using Newtonsoft.Json;
using System;
using System.Web.Mvc;
using VAdvantage.Logging;
using VAdvantage.Utility;
using VASLogic.Models;
using VIS.Filters;

namespace VAS.Controllers
{
    /// <summary>
    /// Module Name : VAS_224_RecentlyGeneratedRecords
    /// Purpose     : Thin AJAX endpoint for the Recently Generated Records dashboard
    ///               widget (Recurring module). All business logic lives in
    ///               VASLogic.Models.VAS_224_RecentlyGeneratedModel; this controller
    ///               only resolves the session context and serializes the result.
    ///               The tenant is always taken from the authenticated context, and
    ///               the look-back window is always derived server side - the client
    ///               supplies neither AD_Client_ID nor a date.
    /// Chronological development:
    ///   VAI154      2026-08-31 Created
    /// </summary>
    public class VAS_224_RecentlyGeneratedRecordsController : Controller
    {
        private static readonly VLogger Log = VLogger.GetVLogger(typeof(VAS_224_RecentlyGeneratedRecordsController).FullName);

        /// <summary>
        /// Returns one page of the documents generated by recurring runs inside the
        /// look-back window, newest first.
        /// </summary>
        /// <param name="page">Zero-based page index. Optional; defaults to the first
        /// page and is clamped in the model.</param>
        /// <param name="pageSize">Rows per page - the widget derives this from its own
        /// cell height. Optional; clamped in the model, so an out-of-range or hostile
        /// value cannot pull an unbounded result set.</param>
        /// <returns>JSON-serialized RecentlyGeneratedPage, "" when there is no
        /// session, or an { error } payload when the lookup fails.</returns>
        [AjaxAuthorizeAttribute]
        [AjaxSessionFilterAttribute]
        public JsonResult GetRecentlyGenerated(int? page, int? pageSize)
        {
            string retJSON = "";

            if (Session["ctx"] != null)
            {
                Ctx ctx = Session["ctx"] as Ctx;
                try
                {
                    int pageIndex = page.HasValue ? page.Value : 0;
                    int size = pageSize.HasValue ? pageSize.Value : VAS_224_RecentlyGeneratedModel.PAGESIZE_DEFAULT;

                    VAS_224_RecentlyGeneratedModel model = new VAS_224_RecentlyGeneratedModel();
                    retJSON = JsonConvert.SerializeObject(model.GetRecentlyGenerated(ctx, pageIndex, size));
                }
                catch (Exception ex)
                {
                    Log.Log(Level.SEVERE, "VAS_224_RecentlyGeneratedRecords.GetRecentlyGenerated", ex);
                    retJSON = JsonConvert.SerializeObject(new { error = true });
                }
            }

            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }
    }
}
