using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VAdvantage.Utility;
using System.Data;
using VAdvantage.Logging;
using VAdvantage.DataBase;
using VAdvantage.ProcessEngine;
using VAdvantage.Model;
using ModelLibrary.Classes;

namespace ViennaAdvantage.Process
{
    public class ProspectToOpportunity : SvrProcess
    {
        int _C_Lead_ID;
        protected override void Prepare()
        {

        }

        /// <summary>
        /// Doit
        /// </summary>
        /// <returns>message</returns>
        protected override string DoIt()
        {
            X_C_BPartner partner = new X_C_BPartner(GetCtx(), GetRecord_ID(), null);
            string _BPName = partner.GetName();
            string _retVal = "";
            string _sql = "SELECT C_Lead_ID FROM C_Lead Where BPName='" + _BPName + "'  AND IsActive = 'Y' AND AD_Client_ID = " + GetAD_Client_ID();
            DataSet ds = DB.ExecuteDataset(_sql.ToString());
            if (ds != null && ds.Tables != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    _C_Lead_ID = Util.GetValueOfInt(ds.Tables[0].Rows[i]["C_Lead_ID"]);
                    X_C_Lead lead = new X_C_Lead(GetCtx(), _C_Lead_ID, Get_TrxName());

                    int Pospect = lead.GetRef_BPartner_ID();

                    if (Pospect != 0)
                    {
                        X_C_Project opp = new X_C_Project(GetCtx(), 0, Get_TrxName());
                        X_C_BPartner bp = new X_C_BPartner(GetCtx(), Pospect, Get_TrxName());
                        //VIA051:- Implement IsCustomer check to verify opportunity is generated by customer or Prospect 
                        if (bp.IsCustomer())
                        {
                            opp.SetC_BPartner_ID(bp.GetC_BPartner_ID());

                        }
                        else
                        {
                            opp.SetC_BPartnerSR_ID(lead.GetRef_BPartner_ID());

                        }
                        opp.SetC_Lead_ID(lead.GetC_Lead_ID());
                        opp.SetName(bp.GetName());
                        opp.SetDescription(lead.GetDescription());
                        opp.SetSalesRep_ID(lead.GetSalesRep_ID());
                        opp.SetDateContract(DateTime.Today);
                        opp.SetC_Campaign_ID(lead.GetC_Campaign_ID());
                        opp.SetAD_User_ID(lead.GetAD_User_ID());
                        opp.SetC_BPartner_Location_ID(lead.GetC_BPartner_Location_ID());
                        opp.SetIsOpportunity(true);
                        // VIA051: changes done to set the value of Ref_BPartner_ID for loading data into Uer/Contact and Location .
                        opp.SetRef_BPartner_ID(lead.GetRef_BPartner_ID());
                        //VAI050-Set below coulum if VA061 module install
                        if (Env.IsModuleInstalled("VA061_"))
                        {
                            opp.Set_Value("VA061_ThreadID", partner.Get_Value("VA061_ThreadID"));
                            opp.Set_Value("VA061_SheetURL", partner.Get_Value("VA061_SheetURL"));
                            opp.Set_Value("VA061_SheetName", partner.Get_Value("VA061_SheetName"));
                            opp.Set_Value("VA061_SheetID", partner.Get_Value("VA061_SheetID"));
                            opp.Set_Value("VA061_SheetPDFURL", partner.Get_Value("VA061_SheetPDFURL"));

                        }

                        if (opp.Save())
                        {
                            //VAI050-Save history chat data form prospect window to opportunity window

                            int FromTableID = partner.Get_Table_ID();
                            int ToTableID = opp.Get_Table_ID();
                            VAS_CommonMethod.CopyHistorRecordData(FromTableID, ToTableID, opp.GetC_Project_ID(), GetRecord_ID(), Get_TrxName(), GetCtx());
                            lead.SetC_Project_ID(opp.GetC_Project_ID());
                            lead.SetProcessed(true);
                            lead.Save();

                            bp.SetCreateProject("Y");
                            if (bp.Save())
                            {
                            }

                            _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateDone");
                        }
                        else
                        {
                            _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateNotDone");
                        }
                    }
                }

            }
            else if (Env.IsModuleInstalled("VA047_"))
            {
                int val = Util.GetValueOfInt(DB.ExecuteScalar("SELECT AD_User_ID FROM AD_User WHERE C_BPartner_ID=" + partner.GetC_BPartner_ID(), null, Get_TrxName())); ;
                X_C_Project opp = new X_C_Project(GetCtx(), 0, Get_TrxName());
                MUser user = new MUser(GetCtx(), val, Get_TrxName());
                opp.SetSalesRep_ID(partner.GetSalesRep_ID());
                opp.SetName(partner.GetName());
                opp.SetDescription(partner.GetDescription());
                opp.SetC_BPartnerSR_ID(partner.GetC_BPartner_ID());
                opp.SetDateContract(DateTime.Today);
                opp.SetAD_User_ID(user.GetAD_User_ID());
                opp.SetC_BPartner_Location_ID(user.GetC_BPartner_Location_ID());
                opp.SetC_Campaign_ID(partner.GetC_Campaign_ID());
                opp.SetIsOpportunity(true);

                if (opp.Save())
                {
                    //VAI050-Set below coulum if VA061 module install
                    if (Env.IsModuleInstalled("VA061_"))
                    {
                        opp.Set_Value("VA061_ThreadID", partner.Get_Value("VA061_ThreadID"));
                        opp.Set_Value("VA061_SheetURL", partner.Get_Value("VA061_SheetURL"));
                        opp.Set_Value("VA061_SheetName", partner.Get_Value("VA061_SheetName"));
                        opp.Set_Value("VA061_SheetID", partner.Get_Value("VA061_SheetID"));
                        opp.Set_Value("VA061_SheetPDFURL", partner.Get_Value("VA061_SheetPDFURL"));

                    }
                    //VAI050-Save history chat data form prospect window to opportunity window
                    int FromTableID = partner.Get_Table_ID();
                    int ToTableID = opp.Get_Table_ID();
                    VAS_CommonMethod.CopyHistorRecordData(FromTableID, ToTableID, opp.GetC_Project_ID(), GetRecord_ID(), Get_TrxName(), GetCtx());
                    partner.SetCreateProject("Y");
                    if (partner.Save())
                    {
                    }
                    _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateDone");
                }
                else
                {
                    _retVal = Msg.GetMsg(GetCtx(), "OpprtunityGenerateNotDone");
                }
            }
            return _retVal;


        }
    }
}
