/**
 * VAS_224_RecentlyGeneratedRecords
 * 6x2 grid widget for the Recurring dashboard.
 *
 * Read-only. Answers "which records were generated by recurring runs in the last
 * 30 days?". No SQL and no DB call is made from the client.
 *
 * Layout (matches the widget.html build pack for this widget):
 *   head   [icon]  Recently Generated Records
 *                  Created by the recurring process in the last 30 days
 *   body   generated | document no | type | business partner | currency | amount
 *   foot   Showing 1–6 of 412                                  < 1 of 69 >
 *
 * Row count adapts to the cell: the body is measured at runtime and the page size
 * is recomputed from it, so the widget shows more rows on a tall dashboard and
 * fewer on a laptop without ever scrolling inside the cell. Paging happens in the
 * database, so a page turn is a fresh request rather than a slice of a downloaded
 * array.
 *
 * Amounts are shown untouched, in the generated document's own currency, with a
 * dedicated currency column beside them - nothing is converted.
 *
 * Summary Message Table
 *  # | Current Text                          | Message Key
 * ---+---------------------------------------+---------------------------------
 *  1 | Recently Generated Records            | VAS_224_RecentlyGenerated
 *  2 | Created by the recurring process in the last {0} days | VAS_224_Subtitle
 *  3 | Generated                             | VAS_224_Generated
 *  4 | Document no                           | VAS_224_DocumentNo
 *  5 | Type                                  | VAS_224_Type
 *  6 | Business partner                      | VAS_224_BusinessPartner
 *  7 | Currency                              | VAS_224_Currency
 *  8 | Amount                                | VAS_224_Amount
 *  9 | Invoice                               | VAS_224_TypeInvoice
 * 10 | Order                                 | VAS_224_TypeOrder
 * 11 | Payment                               | VAS_224_TypePayment
 * 12 | GL Journal                            | VAS_224_TypeGLJournal
 * 13 | GL Journal Batch                      | VAS_224_TypeGLJournalBatch
 * 14 | Project                               | VAS_224_TypeProject
 * 15 | Other                                 | VAS_224_Other
 * 16 | Showing                               | VAS_224_Showing
 * 17 | of                                    | VAS_224_Of
 * 18 | No records generated                  | VAS_224_NoRecordsFound
 * 19 | Loading  (accessible name of the busy indicator) | VAS_224_Loading
 * 20 | Couldn't load                         | VAS_224_CouldntLoad
 * 21 | Previous                              | VAS_224_Previous
 * 22 | Next                                  | VAS_224_Next
 */
; VAS = window.VAS || {};

; (function (VAS, $) {

    function ensureDashInlineSizeVar($el) {
        if (window.__vasDashInlineSizeObserver) { return; }
        if (typeof ResizeObserver === 'undefined') { return; }

        var container = $el.closest('.vis-widget-container, [data-dashboard-container]')[0];
        if (!container) { return; }

        var write = function () {
            document.documentElement.style.setProperty('--dash-inline-size', container.clientWidth + 'px');
        };

        window.__vasDashInlineSizeObserver = new ResizeObserver(write);
        window.__vasDashInlineSizeObserver.observe(container);
        write();
    }

    /* Document-with-check glyph (inline SVG, not an icon-font class - the host shell
       does not always load an icon font and a missing glyph leaves an empty box). */
    var ICON_GENERATED =
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
        'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">' +
        '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>' +
        '<path d="M14 2v6h6"></path>' +
        '<path d="M9 15l2 2 4-4"></path>' +
        '</svg>';

    /* Document type code -> message key + English fallback. The codes are produced by
       VASLogic.Models.VAS_224_RecentlyGeneratedModel and are aligned with
       C_Recurring.RecurringType - keep both sides in lock-step. Labels are never
       resolved in SQL. */
    var TYPE_MAP = {
        'I': { key: 'VAS_224_TypeInvoice', text: 'Invoice' },
        'O': { key: 'VAS_224_TypeOrder', text: 'Order' },
        'P': { key: 'VAS_224_TypePayment', text: 'Payment' },
        'B': { key: 'VAS_224_TypeGLJournal', text: 'GL Journal' },
        'G': { key: 'VAS_224_TypeGLJournalBatch', text: 'GL Journal Batch' },
        'J': { key: 'VAS_224_TypeProject', text: 'Project' }
    };

    /* Approximate rendered height of one body row, used to derive how many rows fit
       the cell. Kept as one constant so the measurement and the row markup can be
       kept in step from a single place. */
    var ROW_HEIGHT_PX = 38;

    /* Never show fewer than this, even if the cell is measured smaller than expected
       mid-layout. */
    var MIN_ROWS = 3;

    /* Mirrors VAS_224_RecentlyGeneratedModel.WINDOW_DAYS. Used only to label the card
       before the first response lands; the rendered value is then taken from the
       window the server actually resolved. */
    var DEFAULT_WINDOW_DAYS = 30;

    VAS.VAS_224_RecentlyGeneratedRecords = function () {

        this.frame;
        this.windowNo;

        var $root = $('<div class="vas-224-root">');
        var $card;
        var $subtitleEl;
        var $bodyEl;
        var $footNoteEl;
        var $pagerEl;

        var widgetObserver = null;
        var bodyObserver = null;
        var listRequest = null;
        var resizeTimer = null;

        var currentPage = 0;

        /* Rows the measured cell can hold - what the widget ASKS the server for. */
        var desiredPageSize = 6;

        /* Rows the server actually served, after its own clamp. Pager maths uses this
           one; the resize decision uses desiredPageSize. Keeping them apart is what
           stops a clamped page size from refetching forever. */
        var pageSize = 6;

        /* Last body height the observer acted on, so an unchanged report is dropped
           instead of scheduling another fetch. */
        var lastMeasuredHeight = 0;

        var totalRows = 0;
        var totalPages = 1;
        var cachedRows = [];

        function label(key, fallback) {
            var translated = VIS.Msg.getMsg(key);
            return (translated && translated.charAt(0) !== '[') ? translated : fallback;
        }

        /* Placeholder substitution for the few messages that carry a value. Kept out
           of SQL and out of the server payload so translators can move the token
           anywhere in the sentence. */
        function format(text, values) {
            var out = String(text == null ? '' : text);
            for (var i = 0; i < values.length; i++) {
                out = out.split('{' + i + '}').join(values[i]);
            }
            return out;
        }

        function escapeHtml(value) {
            return String(value == null ? "" : value)
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }

        /* The endpoint returns a JSON string inside a JSON response, so the payload
           can arrive double-encoded depending on the host serializer. */
        function parseResponse(res) {
            var data = res;
            if (typeof data === 'string') { data = JSON.parse(data); }
            if (typeof data === 'string') { data = JSON.parse(data); }
            return data || {};
        }

        function formatCount(value) {
            var n = Number(value);
            if (!isFinite(n)) { n = 0; }
            return n.toLocaleString(window.navigator.language);
        }

        /* Group and decimal separators follow the user's locale rather than being
           hand-assembled, so the widget reads correctly in both point and comma
           cultures. */
        function formatAmount(value, precision) {
            var n = Number(value);
            if (!isFinite(n)) { n = 0; }
            var p = Number(precision);
            if (!isFinite(p) || p < 0 || p > 6) { p = 2; }
            return n.toLocaleString(window.navigator.language, {
                minimumFractionDigits: p,
                maximumFractionDigits: p
            });
        }

        /* The server transports dates as yyyy-MM-dd; display formatting is the
           client's job. Parsed field by field so the string is never read as UTC and
           shifted a day backwards for users west of Greenwich. */
        function formatDate(iso) {
            if (!iso) { return '—'; }
            var parts = String(iso).split('-');
            if (parts.length !== 3) { return iso; }

            var d = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
            if (isNaN(d.getTime())) { return iso; }

            try {
                return d.toLocaleDateString(window.navigator.language, {
                    day: '2-digit', month: 'short', year: 'numeric'
                });
            } catch (e) {
                return iso;
            }
        }

        function typeLabel(code) {
            var entry = TYPE_MAP[code];
            return entry ? label(entry.key, entry.text) : label("VAS_224_Other", "Other");
        }

        function windowSubtitle(days) {
            return format(
                label("VAS_224_Subtitle", "Created by the recurring process in the last {0} days"),
                [formatCount(days)]
            );
        }

        this.Initalize = function () {
            createWidget();
            setupWidgetObserver();
            setupBodyObserver();
            loadList();
        };

        function setupWidgetObserver() {
            if (typeof ResizeObserver === 'undefined') { return; }
            try {
                widgetObserver = new ResizeObserver(function (entries) {
                    for (var i = 0; i < entries.length; i++) {
                        var width = entries[i].contentRect.width;
                        if (width > 0 && $root[0]) {
                            $root[0].style.setProperty('--widget-inline-size', width + 'px');
                        }
                    }
                });
                widgetObserver.observe($root[0]);
            } catch (e) { }
        }

        /* The visible row count is derived from the cell, not hardcoded: the same
           widget shows fewer rows on a 1280px laptop than on a 2K dashboard, and the
           pager is the contract for "more rows exist".
           The observer must never react to a size change it caused itself, or
           rendering a page would schedule another fetch forever. Two guards: the
           callback ignores any report whose height matches the last one acted on, and
           the decision below compares against the size WE asked for rather than the
           size the server served. */
        function setupBodyObserver() {
            if (typeof ResizeObserver === 'undefined') { return; }
            try {
                bodyObserver = new ResizeObserver(function (entries) {
                    var height = 0;
                    if (entries && entries.length && entries[0].contentRect) {
                        height = Math.round(entries[0].contentRect.height);
                    }

                    /* Sub-pixel churn and repeat reports of an unchanged box are the
                       usual source of an endless refetch loop - drop them here. */
                    if (height === lastMeasuredHeight) { return; }
                    lastMeasuredHeight = height;

                    if (resizeTimer) { window.clearTimeout(resizeTimer); }
                    resizeTimer = window.setTimeout(applyAdaptivePageSize, 200);
                });
                bodyObserver.observe($bodyEl[0]);
            } catch (e) { }
        }

        /* Rows that fit the body box, or 0 while the widget has not been laid out yet
           (it is measured before the framework appends it to the dashboard). */
        function computePageSize() {
            var available = $bodyEl && $bodyEl[0] ? $bodyEl[0].clientHeight : 0;
            if (!available || available <= 0) { return 0; }

            var fits = Math.floor(available / ROW_HEIGHT_PX);
            return Math.max(MIN_ROWS, fits);
        }

        function applyAdaptivePageSize() {
            resizeTimer = null;

            var next = computePageSize();
            if (next <= 0) { return; }

            /* Compared against the REQUESTED size, not the served one. The server
               clamps the page size, so on a very tall cell the served value stays
               below the measured value permanently - comparing against it would leave
               the two never equal and refetch on every single tick. */
            if (next === desiredPageSize) { return; }

            /* Keep the user roughly where they were: the first row of the current
               page stays on screen after the page size changes. Measured against the
               OLD size, then re-expressed in the new one. */
            var firstRowIndex = currentPage * desiredPageSize;
            desiredPageSize = next;
            currentPage = Math.floor(firstRowIndex / desiredPageSize);

            loadList();
        }

        function createWidget() {
            var title = label("VAS_224_RecentlyGenerated", "Recently Generated Records");
            var subtitle = windowSubtitle(DEFAULT_WINDOW_DAYS);

            $card = $(
                '<div class="vas-224-card vas-widget-bg">' +
                '<div class="vas-224-head">' +
                '<span class="vas-224-icon">' + ICON_GENERATED + '</span>' +
                '<span class="vas-224-titles">' +
                '<span class="vas-224-title">' + escapeHtml(title) + '</span>' +
                '<span class="vas-224-subtitle">' + escapeHtml(subtitle) + '</span>' +
                '</span>' +
                '</div>' +
                '<div class="vas-224-thead vas-224-trow vas-224-grid">' +
                headCell(label("VAS_224_Generated", "Generated"), false) +
                headCell(label("VAS_224_DocumentNo", "Document no"), false) +
                headCell(label("VAS_224_Type", "Type"), false) +
                headCell(label("VAS_224_BusinessPartner", "Business partner"), false) +
                headCell(label("VAS_224_Currency", "Currency"), false) +
                headCell(label("VAS_224_Amount", "Amount"), true) +
                '</div>' +
                '<div class="vas-224-body"></div>' +
                '<div class="vas-224-foot">' +
                '<span class="vas-224-foot-note"></span>' +
                '<span class="vas-224-pager"></span>' +
                '</div>' +
                '</div>'
            );

            $subtitleEl = $card.find('.vas-224-subtitle');
            $bodyEl = $card.find('.vas-224-body');
            $footNoteEl = $card.find('.vas-224-foot-note');
            $pagerEl = $card.find('.vas-224-pager');

            $root.append($card);
        }

        function headCell(text, isRight) {
            return '<span class="vas-224-cell' + (isRight ? ' vas-224-c-right' : '') + '" title="' +
                escapeHtml(text) + '">' + escapeHtml(text) + '</span>';
        }

        function loadList() {
            /* A refresh or page turn fired while an earlier request is still open
               would otherwise let the stale response win the race. */
            if (listRequest) {
                listRequest.abort();
                listRequest = null;
            }

            renderLoading();

            listRequest = $.ajax({
                url: VIS.Application.contextUrl + 'VAS_224_RecentlyGeneratedRecords/GetRecentlyGenerated',
                type: 'GET',
                data: { page: currentPage, pageSize: desiredPageSize },
                cache: false,
                success: function (res) {
                    var data;
                    try {
                        data = parseResponse(res);
                    } catch (e) {
                        renderError();
                        return;
                    }

                    if (data.error || !data.Loaded) { renderError(); return; }
                    renderList(data);
                },
                error: function (xhr, status) {
                    /* An aborted request is this widget superseding itself, not a
                       failure - the newer request owns the body. */
                    if (status === 'abort') { return; }
                    renderError();
                },
                complete: function () {
                    listRequest = null;
                }
            });
        }

        /* The platform busy indicator, not a text line - the same spinner the rest of
           the Recurring family uses. The label survives as the accessible name so the
           state is still announced.
           The footer is deliberately left standing: emptying it would change its
           height, which changes the body height, which wakes the resize observer and
           starts another fetch. The pager is disabled in place instead of removed. */
        function renderLoading() {
            $bodyEl.html(
                '<div class="vas-224-state vas-224-state-busy" role="status" aria-live="polite" ' +
                'aria-label="' + escapeHtml(label("VAS_224_Loading", "Loading")) + '">' +
                '<div class="vis-busyindicatorinnerwrap"><i class="vis_widgetloader"></i></div>' +
                '</div>'
            );
            $pagerEl.find('[data-page]').prop('disabled', true);
        }

        function renderError() {
            cachedRows = [];

            var msg = label("VAS_224_CouldntLoad", "Couldn't load");
            $bodyEl.html('<div class="vas-224-state vas-224-state-error">' + escapeHtml(msg) + '</div>');
            $footNoteEl.text(msg).attr('title', msg);
            $pagerEl.empty();
        }

        function renderList(data) {
            cachedRows = data.Rows || [];

            /* The server clamps the page index, so a stale page number is corrected
               rather than returning an unexplained empty list. */
            currentPage = Number(data.Page) || 0;
            pageSize = Number(data.PageSize) || pageSize;
            totalRows = Number(data.TotalRows) || 0;
            totalPages = Math.max(1, Math.ceil(totalRows / pageSize));

            /* The server clamps the window too, so the card names the span it really
               queried rather than the one that was asked for. */
            var subtitle = windowSubtitle(Number(data.WindowDays) || DEFAULT_WINDOW_DAYS);
            $subtitleEl.text(subtitle).attr('title', subtitle);

            renderRows();
            renderFooter();
        }

        function renderRows() {
            if (cachedRows.length === 0) {
                $bodyEl.html('<div class="vas-224-state">' +
                    escapeHtml(label("VAS_224_NoRecordsFound", "No records generated")) + '</div>');
                return;
            }

            var html = '';

            for (var i = 0; i < cachedRows.length; i++) {
                var row = cachedRows[i];

                var dateText = formatDate(row.GeneratedDate);
                var docNoText = row.DocumentNo || '—';
                var typeText = typeLabel(row.DocumentType);

                /* A document with no partner reference shows the same em-dash
                   placeholder the other empty cells use - GL journals are the usual
                   case, since they post against the ledger. */
                var partnerText = row.BPartnerName ? row.BPartnerName : '—';

                /* The figure is the generated document's own, formatted to that
                   currency's standard precision - a zero-decimal currency must not be
                   printed with two. */
                var amountText = formatAmount(row.Amount, row.AmountPrecision);
                var currencyText = row.AmountCurrencyIso || '—';
                var currencyTitle = row.AmountCurrencySymbol
                    ? (currencyText + ' · ' + row.AmountCurrencySymbol)
                    : currencyText;
                var amountTitle = amountText + (row.AmountCurrencyIso ? ' ' + row.AmountCurrencyIso : '');

                html +=
                    '<div class="vas-224-trow vas-224-grid vas-224-body-row">' +
                    '<span class="vas-224-cell vas-224-c-num" title="' + escapeHtml(dateText) + '">' + escapeHtml(dateText) + '</span>' +
                    '<span class="vas-224-cell vas-224-c-prim" title="' + escapeHtml(docNoText) + '">' + escapeHtml(docNoText) + '</span>' +
                    '<span class="vas-224-cell vas-224-c-std" title="' + escapeHtml(typeText) + '">' + escapeHtml(typeText) + '</span>' +
                    '<span class="vas-224-cell vas-224-c-std" title="' + escapeHtml(partnerText) + '">' + escapeHtml(partnerText) + '</span>' +
                    '<span class="vas-224-cell vas-224-c-cur" title="' + escapeHtml(currencyTitle) + '">' + escapeHtml(currencyText) + '</span>' +
                    '<span class="vas-224-cell vas-224-c-val" title="' + escapeHtml(amountTitle) + '">' + escapeHtml(amountText) + '</span>' +
                    '</div>';
            }

            $bodyEl.html(html);
        }

        function renderFooter() {
            var start = currentPage * pageSize;

            var note = '';
            if (totalRows > 0) {
                note = label("VAS_224_Showing", "Showing") + ' ' + (start + 1) + '–' + (start + cachedRows.length)
                    + ' ' + label("VAS_224_Of", "of") + ' ' + formatCount(totalRows);
            }
            $footNoteEl.text(note).attr('title', note);

            var pagerHtml = '';
            if (totalPages > 1) {
                pagerHtml =
                    '<button type="button" class="vas-224-pbtn" data-page="prev"' + (currentPage === 0 ? ' disabled' : '') +
                    ' aria-label="' + escapeHtml(label("VAS_224_Previous", "Previous")) + '">' +
                    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>' +
                    '</button>' +
                    '<span class="vas-224-ptxt">' + (currentPage + 1) + ' ' + escapeHtml(label("VAS_224_Of", "of")) + ' ' + totalPages + '</span>' +
                    '<button type="button" class="vas-224-pbtn" data-page="next"' + (currentPage >= totalPages - 1 ? ' disabled' : '') +
                    ' aria-label="' + escapeHtml(label("VAS_224_Next", "Next")) + '">' +
                    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg>' +
                    '</button>';
            }

            $pagerEl.html(pagerHtml);
            $pagerEl.find('[data-page]').on('click', function () {
                var dir = $(this).attr('data-page');
                if (dir === 'prev' && currentPage > 0) { currentPage--; }
                else if (dir === 'next' && currentPage < totalPages - 1) { currentPage++; }
                else { return; }
                loadList();
            });
        }

        /* Called by the platform Refresh button and whenever the host dashboard
           re-broadcasts a record change on the Recurring window. */
        this.refreshWidget = function () {
            loadList();
        };

        this.getRoot = function () { return $root; };

        this.disposeComponent = function () {
            if (listRequest) { listRequest.abort(); listRequest = null; }
            if (resizeTimer) { window.clearTimeout(resizeTimer); resizeTimer = null; }

            if (widgetObserver) {
                try { widgetObserver.disconnect(); } catch (e) { }
                widgetObserver = null;
            }
            if (bodyObserver) {
                try { bodyObserver.disconnect(); } catch (e) { }
                bodyObserver = null;
            }

            if ($pagerEl) { $pagerEl.find('[data-page]').off(); }

            $root.remove();
        };
    };

    VAS.VAS_224_RecentlyGeneratedRecords.prototype.widgetFirevalueChanged = function (value) {
        if (this.listener) { this.listener.widgetFirevalueChanged(value); }
    };

    VAS.VAS_224_RecentlyGeneratedRecords.prototype.addChangeListener = function (listener) {
        this.listener = listener;
    };

    VAS.VAS_224_RecentlyGeneratedRecords.prototype.init = function (windowNo, frame) {
        this.frame = frame;
        this.AD_UserHomeWidgetID = frame.widgetInfo.AD_UserHomeWidgetID;
        this.windowNo = windowNo;
        this.Initalize();
        this.frame.getContentGrid().append(this.getRoot());
        ensureDashInlineSizeVar(this.getRoot());
    };

    VAS.VAS_224_RecentlyGeneratedRecords.prototype.widgetSizeChange = function (height, width) { };

    VAS.VAS_224_RecentlyGeneratedRecords.prototype.dispose = function () {
        this.disposeComponent();
        if (this.frame) { this.frame.dispose(); }
        this.frame = null;
    };

})(VAS, jQuery);
